### PR TITLE
stackified, removed explicit lower bounds, effectively enabling usage…

### PR DESCRIPTION
**Pull request by michaxm**
… with ghc-7.8

note: seemed to cause an additional dependency on the libgsasl system library, I have not tried to analyze the dependency graph for that

### CODE REVIEW

**Comment by jystic** [comment]
I'm all for ghc-7.8 support, and the stack.yaml is ok too, but I'm not ok with removing all the bounds

The `libgsasl` was added by @luke-clifton in an earlier PR for Kerberos support, so that's all good

**Comment by michaxm** [comment]
I am all for stack since I started using it, I assume you plan on keeping the bounds for supporting non-stack users?
Fine by me, but I would not want to figure out manually, which package versions would be ok for ghc-7.8 now that we have tools for that. I consider the need for explicit versions in cabal files a relict of the past now ...

Shall I look which versions stack figured out to allow for 7.8 and change the bounds accordingly? I would only do it, if you consider that an improvement, otherwise we should abandon this change altogether.

**Comment by jystic** [comment]
> I am all for stack since I started using it, I assume you plan on keeping the bounds for supporting non-stack users?

Yeah that's right, we don't use stack at work and I don't use it personally either. We have our own [tool](https://github.com/ambiata/mafia) which makes working with cabal pretty pleasant. (unfortunately it's  very poorly documented atm, so not really fit for public consumption yet, sorry :disappointed:)

> Fine by me, but I would not want to figure out manually, which package versions would be ok for ghc-7.8 now that we have tools for that.

Sorry to nitpick, but saying "we have tools for that" is a bit of a stretch, stack and stackage work smoothly because of a large amount of human effort and coordination, not tooling. It's great if you're happy to use the versions of things dictated by stackage, but for some people that's not an acceptable choice.

In this case, cabal resolves an install plan for ghc-7.8.4 no problem, without any modifications to the .cabal file, so it's only stack that has an issue here, and it's because stackage has pinned you to old versions of packages on ghc-7.8.4.

> Shall I look which versions stack figured out to allow for 7.8 and change the bounds accordingly?  I would only do it, if you consider that an improvement, otherwise we should abandon this change altogether.

Yeah if you find the versions that stack needs to resolve a plan, I'll be happy to lower the bounds. Having said that, I don't have any plans to use stack, so only go to the trouble if you'd like this for yourself or other stack users.

**Comment by michaxm** [comment]
After hunting the dependencies down, I totally agree. Being a bit blinded by stack and "it just works!" I suspected a real reason why base versions due to other bounds. But in this case requiring transformers 0.4 instead of 0.3 is the only thing preventing the stackage 2.22 build plan (for 7.8), it just does not provide out of the box a good plan for this constellation.

That said, these plans have the potential to provide sensible defaults to make dependency hunting much more easier for the most of us.

Note: I updated the pull request in place (via --force on that branch), in hindsight I am unsure, if that was a good idea. Looks good to me, but it seems it did not trigger another build.

Split stack in a different commit than lowering transformers? Sorry for the long discussion, this is clearly too much meta for such a trivial commit ...

**Comment by jystic** [comment]
> That said, these plans have the potential to provide sensible defaults to make dependency hunting much more easier for the most of us.

For sure, would be great if we could generate this kind of thing with tooling though, so that we don't get locked in to the "one true stackage" set of dependencies. I worry what happens when you're still supporting something on an old GHC (i.e. 7.8.4) and you discover a security issue in one of the packages you use, but stackage has it pinned. I'm sure you can put a PR up on stackage to resolve the issue, but having to coordinate with the rest of the world doesn't exactly make for a timely fix.

> Note: I updated the pull request in place (via --force on that branch), in hindsight I am unsure, if that was a good idea. Looks good to me though, build was triggered ...

Yep that's perfect :zap: 

> Split stack in a different commit than lowering transformers? Sorry for the long discussion, this is clearly too much meta for such a trivial commit ...

That's ok, I don't mind :palm_tree:

This all looks good, merging :+1:

**Comment by jystic** [comment]
Annoyingly, github seems to have lost the ability to detect that this PR is the same as the rebased commit which I just merged to master. Anyhow, all merged :+1:

**Pull request closed without merging**
